---
vector-version: "0.31.0"
vector-config:
  sources:
    sample_file:
      type: file
      read_from: beginning
      ignore_older_secs: 600
      include:
        - /home/odmin/logs/*.log
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - sample_file
      endpoints:
      databases:
      table:
      auth:
        user: odmin
      skip_unknowm_fields: true
      commpression: gzip
