version: "3"
services:
  teamcity:
    image: jetbrains/teamcity-server
    volumes:
      - ~/teamcity/data/:/data/teamcity_server/datadir
      - ~/teamcity/logs/:/opt/teamcity/logs
    ports:
      - 8111:8111
  teamcity-agent:
    image: jetbrains/teamcity-agent
    depends_on:
      - teamcity
    volumes:
      - ~/teamcity/agent/:/data/teamcity_agent/conf 
    environment:
      SERVER_URL: "http://192.168.31.100:8111"
  nexus:
    image: sonatype/docker-nexus3
    ports:
      - 8081:8081
    volumes:
      - ~/nexus-data:/nexus-data